base/urls.py
"""urlconf for the base application"""

from django.conf.urls import url, patterns


urlpatterns = patterns('base.views',
    url(r'^$', 'home', name='home'),
)

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, DetailView
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model

from forms import EmailAuthenticateForm
from views import UserUpdateView, UserCreateView

urlpatterns = patterns(
    '',
    url(
        r'^password-reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset'
    ),
    url(
        r'^login/$',
        'django.contrib.auth.views.login',
        {'authentication_form': EmailAuthenticateForm},
        name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^register/$', UserCreateView.as_view(), name='register'),
    url(r'^edit/$', login_required(UserUpdateView.as_view()), name='user-edit'),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(model=get_user_model()),
        name='user-detail'),
    url(r'^register/success/',
        TemplateView.as_view(
            template_name='registration/register_success.html'),
        name='register-success'),
    url(r'^', include('django.contrib.auth.urls')),
)

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from itertools import izip

from pytz import common_timezones
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from utils.annoying import nullable
from managers import EmailUserManager


class Referer(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return u'{0}'.format(self.name)


class User(AbstractBaseUser, PermissionsMixin):
    MALE = 1
    FEMALE = 2
    GENDER_CHOICES = (
        (MALE, 'Мужской'),
        (FEMALE, 'Женский')
    )

    TIMEZONE_CHOICES = izip(common_timezones, common_timezones)

    email = models.EmailField(
        _('Электронная почта'), max_length=255, unique=True, db_index=True)
    first_name = models.CharField(_('Имя'), max_length=30, **nullable)
    last_name = models.CharField(_('Фамилия'), max_length=30, **nullable)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_active = models.BooleanField(
        _('active'), default=False,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    is_staff = models.BooleanField(
        _('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    # Info fields
    url = models.URLField('Профиль в вк/фб', **nullable)
    gender = models.IntegerField('Пол', choices=GENDER_CHOICES, **nullable)
    birth_date = models.DateField('Дата рождения', **nullable)
    phone_number = models.CharField('Номер телефона', max_length=22, **nullable)
    is_available = models.BooleanField(default=True)
    arrive_date = models.DateTimeField(**nullable)
    timezone = models.CharField(
        'Часовой пояс', max_length=30, choices=TIMEZONE_CHOICES,
        default='Asia/Bangkok')
    bio = models.TextField(
        _('О себе'), help_text=_('Расскажите немного о себе'), **nullable)
    userpic_origin = models.ImageField('Аватар', upload_to='userpic',
                                help_text=_('Выберите изображение'), **nullable)
    comment = models.TextField('Комментарий', **nullable)

    referer = models.ForeignKey(Referer, **nullable)
    need_sleeping = models.BooleanField(default=True)
    pastimes = models.ManyToManyField('pastimes.Pastime',
                                       related_name='users', **nullable)

    objects = EmailUserManager()

    EMAIL_FIELD = USERNAME_FIELD = 'email'

    def __unicode__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('user-detail', args=(self.pk,))

    def get_full_name(self):
        return ' '.join(filter(bool, (
            self.first_name, self.last_name))) or self.email

    def get_short_name(self):
        return '' # TODO NotImplementedError

users/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import authenticate, get_user_model


class LowerEmailMixin:
    def clean_email(self):
        return self.cleaned_data["email"].lower()


class EmailAuthenticateForm(LowerEmailMixin, forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    email = forms.EmailField(max_length=255)
    password = forms.CharField(label=_("Пароль"), widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': _("Пожалуйста, проверьте правильность ввода "
                           "электронной почты и пароля. "
                           "Обратите внимание на то, что оба поля "
                           "чувствительны к регистру."),
        'no_cookies': _("Your Web browser doesn't appear to have cookies "
                        "enabled. Cookies are required for logging in."),
        'inactive': _("Акаунт не активирован."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        If request is passed in, the form will validate that cookies are
        enabled. Note that the request (a HttpRequest object) must have set a
        cookie with the key TEST_COOKIE_NAME and value TEST_COOKIE_VALUE before
        running this validation.
        """
        self.request = request
        self.user_cache = None
        super(EmailAuthenticateForm, self).__init__(*args, **kwargs)

        # Set the label for the "username" field.
        UserModel = get_user_model()
        email_field = UserModel._meta.get_field(UserModel.EMAIL_FIELD)
        self.fields[UserModel.EMAIL_FIELD].label = capfirst(
            email_field.verbose_name)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'])
            elif not self.user_cache.is_active:
                raise forms.ValidationError(self.error_messages['inactive'])
        self.check_for_test_cookie()
        return self.cleaned_data

    def check_for_test_cookie(self):
        if self.request and not self.request.session.test_cookie_worked():
            raise forms.ValidationError(self.error_messages['no_cookies'])

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class RegistrationForm(LowerEmailMixin, forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    error_messages = {
        'duplicate_email': _("Плоьзователь с таким именем уже существует."),
        'password_mismatch': _("Пароли не совпадают."),
    }
    password1 = forms.CharField(label=_("Пароль"), widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_("Подтверждение пароля"), widget=forms.PasswordInput,
        help_text=_("Введите еще раз тот же пароль для проверки."))

    class Meta:
        model = get_user_model()
        fields = ("email",)

    def clean_email(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        email = super(RegistrationForm, self).clean_email()
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(self.error_messages['duplicate_email'])

        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserUpdateForm(LowerEmailMixin, forms.ModelForm):
    class Meta:
        model = get_user_model()
        excludes = ('residence', 'timezone', 'bio', 'is_staff', 'is_active')


class AdminUserCreationForm(LowerEmailMixin, forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        excludes = ('residence', 'timezone', 'bio', 'is_staff', 'is_active')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(AdminUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class AdminUserChangeForm(LowerEmailMixin, forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = get_user_model()

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

users/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.views.generic import CreateView, UpdateView
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from forms import RegistrationForm, UserUpdateForm


class UserCreateView(CreateView):
    model = get_user_model()
    template_name = 'registration/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('register-success')


class UserUpdateView(UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return self.request.path

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            messages.success(request, 'Профиль успешно обновлен.')
            return self.form_valid(form)
        else:
            messages.error(request, 'Ошибка при сохранении профиля.')
            return self.form_invalid(form)

users/templates/users/user_form.html
{% extends "_layouts/base.html" %}
{% load i18n staticfiles %}

{% block title %}{{ user.get_full_name }} {% trans 'profile' %}{% endblock %}
{% block header-title %}Личный кабинет{% endblock %}

{% block content %}
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    <div class="u-wrapper">
        <form class="profile-form" method="post" action="{% url 'user-edit' %}" enctype="multipart/form-data">
            <fieldset>
                {% csrf_token %}
                {{ form }}
{#                <div class="row important">#}
{#                    <label class="profile-label" for="id_first_name">Имя</label>#}
{#                    {{ form.first_name }}#}
{#                </div>#}
{#                <div class="row important">#}
{#                    <label class="profile-label" for="id_last_name">Фамилия</label>#}
{#                    {{ form.last_name }}#}
{#                </div>#}
{#                <div class="row">#}
{#                    <label class="profile-label" for="id_birth_date">Дата рождения</label>#}
{#                    {{ form.birth_date }}#}
{#                </div>#}
{#                <div class="row">#}
{#                    <label class="profile-label">Пол</label>#}
{#                    {{ form.gender }}#}
{#                </div>#}
{#                <div class="row">#}
{#                    <label class="profile-label" for="id_phone_number">Телефон</label>#}
{#                    {{ form.phone_number }}#}
{#                </div>#}
{#                <div class="row">#}
{#                    <label class="profile-label" for="id_country">Страна</label>#}
{#                    {{ form.country }}#}
{#                </div>#}
{#                <div class="row">#}
{#                    <label class="profile-label" for="id_residence">Город</label>#}
{#                    {{ form.residence }}#}
{#                </div>#}
{#                <div class="row">#}
{#                    <label class="profile-label" for="id_bio">Дополнительная информация</label>#}
{#                    {{ form.bio }}#}
{#                </div>#}
{#                <div class="user-photo">#}
{#                    {{ form.userpic_origin }}#}
{#                    <output id="show-add-image">#}
{#                    {% if user.userpic_origin %}#}
{#                        <img src="{% url 'image-crop-resize' '' user.userpic_origin.name %}?width=140&height=140" alt="{{ user.get_full_name }}"/>#}
{#                    {% endif %}#}
{#                    </output>#}
{#                </div>#}
                <input type="submit" value="Сохранить"/>
            </fieldset>
        </form>
    </div>
{% endblock %}
{% block js %}
     <script src="{% static 'js/js/profile.js' %}"></script>
     <script>
        $(function() {
            $( "#id_birth_date" ).datepicker({
                autoSize: true,
	            changeMonth: true,
				changeYear: true,
	            yearRange: "1940:2012"
            });

            _.delay(function() {
                $('.messages').fadeOut();
            }, 1500)
        });
    </script>
{% endblock %}